# Copied from:
# https://github.com/omniauth/omniauth/blob/master/.travis.yml
before_install: gem update bundler
cache: bundler
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
language: ruby
rvm:
  - jruby-9000
  - 2.1.10 # EOL Soon
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
sudo: false
